### SE(AI&DS) - Bhavya Damani_10





In [ ]:
import numpy as np

# 1. Array Creation Techniques
print("1. Array Creation Techniques")

# a. Creating an array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

# b. Using arange()
array_arange = np.arange(0, 10, 2)
print(array_arange)

# c. Using linspace()
array_linspace = np.linspace(0, 10, 5)  # Divides 0 to 10 into 5 points
print(array_linspace)

# d. Using zeros()
array_zeros = np.zeros((3, 3))
print(array_zeros)

# e. Using ones()
array_ones = np.ones((2, 2))
print(array_ones)

# f. Using eye() for identity matrix
array_eye = np.eye(3)
print(array_eye)

# g. Using random() for random values
array_random = np.random.random((3, 3))
print(array_random)

# 2. Different NumPy Methods
print("\n2. NumPy Methods")

# a. Reshaping an array
reshaped_array = np.arange(1, 10).reshape(3, 3)
print(reshaped_array)

# b. Transposing an array
transposed_array = reshaped_array.T
print(transposed_array)

# c. Mathematical operations
array_math = np.array([1, 2, 3])
array_math + 2
array_math * 3
print(np.sqrt(array_math))

# d. Aggregation methods
print(np.sum(array_math))
print(np.mean(array_math))
print(np.max(array_math))
print(np.min(array_math))

# e. Concatenation of arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concat_array = np.concatenate((array_a, array_b))
print(concat_array)

# f. Sorting an array
unsorted_array = np.array([3, 1, 4, 2])
sorted_array = np.sort(unsorted_array)
print(sorted_array)

# g. Indexing and Slicing
indexed_value = array_math[1]  # Indexing
print(indexed_value)
sliced_array = array_math[1:3]  # Slicing
print(sliced_array)

# h. Boolean Masking
boolean_mask = array_math > 2
boolean_mask
print(array_math[boolean_mask])

1. Array Creation Techniques
[1 2 3 4 5]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.86922194 0.80186247 0.39936681]
 [0.16581643 0.70514118 0.52405189]
 [0.36445304 0.86619081 0.54807606]]

2. NumPy Methods
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1.         1.41421356 1.73205081]
6
2.0
3
1
[1 2 3 4 5 6]
[1 2 3 4]
2
[2 3]
[3]
